module.exports = [
    ['modules_modules', 'module (模块)'],
    ['modules_accessing_the_main_module', '访问主模块'],
    ['modules_addenda_package_manager_tips', '附录：包管理器的技巧'],
    ['modules_all_together', '总结'],
    ['modules_caching', '缓存'],
    ['modules_module_caching_caveats', '模块缓存的注意事项'],
    ['modules_core_modules', '核心模块'],
    ['modules_cycles', '循环'],
    ['modules_file_modules', '文件模块'],
    ['modules_folders_as_modules', '目录作为模块'],
    ['modules_loading_from_node_modules_folders', '从 <code>node_modules</code> 目录加载'],
    ['modules_loading_from_the_global_folders', '从全局目录加载'],
    ['modules_the_module_wrapper', '模块包装器'],
    ['modules_the_module_object', 'module 对象'],
    ['modules_exports_shortcut', 'exports 快捷方式'],
]