module.exports = [
    ['buffer_buffer', 'Buffer (缓冲)'],
    ['buffer_the_zero_fill_buffers_command_line_option', '<code>--zero-fill-buffers</code> 命令行选项'],
    ['buffer_what_makes_buffer_allocunsafe_and_buffer_allocunsafeslow_unsafe', '是什么令 <code>Buffer.allocUnsafe()</code> 和 <code>Buffer.allocUnsafeSlow()</code> 不安全？'],
    ['buffer_buffers_and_character_encodings', 'Buffer 与字符编码'],
    ['buffer_buffers_and_typedarray', 'Buffer 与 TypedArray'],
    ['buffer_buffers_and_es6_iteration', 'Buffer 与 ES6 迭代器'],
    ['buffer_class_buffer', 'Buffer 类'],
    ['buffer_class_method_buffer_alloc_size_fill_encoding', '类方法：Buffer.alloc(size[, fill[, encoding]])'],
    ['buffer_class_method_buffer_allocunsafe_size', '类方法：Buffer.allocUnsafe(size)'],
    ['buffer_class_method_buffer_allocunsafeslow_size', '类方法：Buffer.allocUnsafeSlow(size)'],
    ['buffer_class_method_buffer_bytelength_string_encoding', '类方法：Buffer.byteLength(string[, encoding])'],
    ['buffer_class_method_buffer_compare_buf1_buf2', '类方法：Buffer.compare(buf1, buf2)'],
    ['buffer_class_method_buffer_concat_list_totallength', '类方法：Buffer.concat(list[, totalLength])'],
    ['buffer_class_method_buffer_from_array', '类方法：Buffer.from(array)'],
    ['buffer_class_method_buffer_from_arraybuffer_byteoffset_length', '类方法：Buffer.from(arrayBuffer[, byteOffset[, length]])'],
    ['buffer_class_method_buffer_from_buffer', '类方法：Buffer.from(buffer)'],
    ['buffer_class_method_buffer_from_string_encoding', '类方法：Buffer.from(string[, encoding])'],
    ['buffer_class_method_buffer_isbuffer_obj', '类方法：Buffer.isBuffer(obj)'],
    ['buffer_class_method_buffer_isencoding_encoding', '类方法：Buffer.isEncoding(encoding)'],
    ['buffer_class_property_buffer_poolsize', '类属性：Buffer.poolSize'],
    ['buffer_class_slowbuffer', 'SlowBuffer 类'],
]