module.exports = [
    ['http_http', 'http'],
    ['http_class_http_agent', 'http.Agent 类'],
    ['http_class_http_clientrequest', 'http.ClientRequest 类'],
    ['http_event_abort', "'abort' 事件"],
    ['http_event_aborted', "'aborted' 事件"],
    ['http_event_connect', "'connect' 事件"],
    ['http_event_continue', "'continue' 事件"],
    ['http_event_response', "'response' 事件"],
    ['http_event_socket', "'socket' 事件"],
    ['http_event_upgrade', "'upgrade' 事件"],
    ['http_class_http_server', 'http.Server 类'],
    ['http_event_checkcontinue', "'checkContinue' 事件"],
    ['http_event_checkexpectation', "'checkExpectation' 事件"],
    ['http_event_clienterror', "'clientError' 事件"],
    ['http_event_close', "'close' 事件"],
    ['http_event_connect_1', "'connect' 事件"],
    ['http_event_connection', "'connection' 事件"],
    ['http_event_request', "'request' 事件"],
    ['http_event_upgrade_1', "'upgrade' 事件"],
    ['http_class_http_serverresponse', 'http.ServerResponse 类'],
    ['http_event_close_1', "'close' 事件"],
    ['http_event_finish', "'finish' 事件"],
    ['http_class_http_incomingmessage', 'http.IncomingMessage 类'],
    ['http_event_aborted_1', "'aborted' 事件"],
    ['http_event_close_2', "'close' 事件"],
]