module.exports = [
    ['stream_stream', 'stream (流)'],
    ['stream_organization_of_this_document', '本文档的组织'],
    ['stream_types_of_streams', '流的类型'],
    ['stream_object_mode', '对象模式'],
    ['stream_buffering', '缓冲'],
    ['stream_api_for_stream_consumers', '流消费者的 API'],
    ['stream_writable_streams', '可写流'],
    ['stream_class_stream_writable', 'stream.Writable 类'],
    ['stream_event_close', "'close' 事件"],
    ['stream_event_drain', "'drain' 事件"],
    ['stream_event_error', "'error' 事件"],
    ['stream_event_finish', "'finish' 事件"],
    ['stream_event_pipe', "'pipe' 事件"],
    ['stream_event_unpipe', "'unpipe' 事件"],
    ['stream_readable_streams', '可读流'],
    ['stream_two_modes', '两种模式'],
    ['stream_three_states', '三种状态'],
    ['stream_choose_one', '选择一种'],
    ['stream_class_stream_readable', 'stream.Readable 类'],
    ['stream_event_close_1', "'close' 事件"],
    ['stream_event_data', "'data' 事件"],
    ['stream_event_end', "'end' 事件"],
    ['stream_event_error_1', "'error' 事件"],
    ['stream_event_readable', "'readable' 事件"],
    ['stream_duplex_and_transform_streams', 'Duplex 流与 Transform 流'],
    ['stream_class_stream_duplex', 'stream.Duplex 类'],
    ['stream_class_stream_transform', 'stream.Transform 类'],
    ['stream_an_example_writable_stream', '一个可写流的例子'],
    ['stream_an_example_counting_stream', '一个数流的例子'],
]