module.exports = [
    ['addons_c_addons', 'C++ 插件'],
    ['addons_building', '构建'],
    ['addons_linking_to_node_js_own_dependencies', '链接到 Node.js 自有的依赖'],
    ['addons_loading_addons_using_require', '使用 require() 加载插件'],
    ['addons_native_abstractions_for_node_js', 'Node.js 的原生抽象'],
    ['addons_addon_examples', '插件示例'],
    ['addons_function_arguments', '函数的参数'],
    ['addons_callbacks', '回调'],
    ['addons_object_factory', '对象工厂'],
    ['addons_function_factory', '函数工厂'],
    ['addons_wrapping_c_objects', '包装 C++ 对象'],
    ['addons_factory_of_wrapped_objects', '包装对象的工厂'],
    ['addons_passing_wrapped_objects_around', '传递包装的对象'],
    ['addons_atexit_hooks', 'AtExit 钩子'],
]