module.exports = [
    ['fs_file_system', 'fs (文件系统)'],
    ['fs_class_fs_fswatcher', 'fs.FSWatcher 类'],
    ['fs_event_change', "'change' 事件"],
    ['fs_event_error', "'error' 事件"],
    ['fs_class_fs_readstream', 'fs.ReadStream 类'],
    ['fs_event_open', "'open' 事件"],
    ['fs_event_close', "'close' 事件"],
    ['fs_class_fs_stats', 'fs.Stats 类'],
    ['fs_stat_time_values', 'Stat 时间值'],
    ['fs_class_fs_writestream', 'fs.WriteStream 类'],
    ['fs_event_open_1', "'open' 事件"],
    ['fs_event_close_1', "'close' 事件"],
    ['fs_caveats', '说明'],
    ['fs_availability', '可用性'],
    ['fs_inodes', '索引节点'],
    ['fs_filename_argument', '文件名参数'],
    ['fs_fs_constants_1', 'fs 常量'],
    ['fs_file_access_constants', '文件访问常量'],
    ['fs_file_open_constants', '文件打开常量'],
    ['fs_file_type_constants', '文件类型常量'],
    ['fs_file_mode_constants', '文件模式常量']
]