module.exports = [
    ['repl_repl', 'repl (交互式解释器)'],
    ['repl_design_and_features', '设计与特性'],
    ['repl_commands_and_special_keys', '命令与特殊键'],
    ['repl_default_evaluation', '默认的解释器'],
    ['repl_javascript_expressions', 'JavaScript 表达式'],
    ['repl_global_and_local_scope', '全局作用域与局部作用域'],
    ['repl_accessing_core_node_js_modules', '访问 Node.js 核心模块'],
    ['repl_assignment_of_the_underscore_variable', '<code>_</code>（下划线）变量的赋值'],
    ['repl_custom_evaluation_functions', '自定义的解释函数'],
    ['repl_recoverable_errors', '可恢复的错误'],
    ['repl_customizing_repl_output', '自定义 REPL 输出'],
    ['repl_class_replserver', 'REPLServer 类'],
    ['repl_event_exit', "'exit' 事件"],
    ['repl_event_reset', "'reset' 事件"],
    ['repl_the_node_js_repl', 'Node.js 的 REPL'],
    ['repl_environment_variable_options', '环境变量选项'],
    ['repl_persistent_history', '历史记录'],
    ['repl_using_the_node_js_repl_with_advanced_line_editors', '在高级的行编辑器中使用 Node.js REPL'],
    ['repl_starting_multiple_repl_instances_against_a_single_running_instance', '在一个 Node.js 实例中启动多个 REPL 实例'],
]