module.exports = [
    ['child_process_child_process', 'child_process (子进程)'],
    ['child_process_asynchronous_process_creation', '创建异步进程'],
    ['child_process_spawning_bat_and_cmd_files_on_windows', '在 Windows 上衍生 <code>.bat</code> 和 <code>.cmd</code> 文件'],
    ['child_process_synchronous_process_creation', '创建同步进程'],
    ['child_process_class_childprocess', 'ChildProcess 类'],
    ['child_process_event_close', "'close' 事件"],
    ['child_process_event_disconnect', "'disconnect' 事件"],
    ['child_process_event_error', "'error' 事件"],
    ['child_process_event_exit', "'exit' 事件"],
    ['child_process_event_message', "'message' 事件"],
    ['child_process_example_sending_a_server_object', '例子：发送一个 server 对象'],
    ['child_process_example_sending_a_socket_object', '例子：发送一个 socket 对象'],
    ['child_process_maxbuffer_and_unicode', '<code>maxBuffer</code> 与 Unicode'],
]